### Get Request Example
GET http://localhost:4000/api/items

### post Request Example
POST http://localhost:4000/api/items
Content-Type: application/json

{
  "name": "Bike helmet",
  "description": "keeps your head safe"
}